#!/usr/bin/env python
import os

def testf(fn): 
    import json
    print "Testing %s..." % fn
    void = json.load(open(fn))

def testd(arg, dirname, fnames):
    for fn in fnames:
        if fn.endswith('.json'):
            testf(os.path.join(dirname, fn))

os.path.walk('datamodel', testd, None)

