#!/usr/bin/env python
import os

#schema_file = 'datamodel-v1-schema.json'
schema_file = 'schema.alt.json'

try:
    import jsonschema, json
    schema = json.load(open(schema_file))
    validator = jsonschema.Draft4Validator(schema)
    def testf(fn):
        print "Testing %s..." % fn
        if False:
            for error in sorted(validator.iter_errors(json.load(open(fn))), key=str):
                print error.message
        else:
            validator.validate(json.load(open(fn)))


except ImportError:
    print "JSON Schema not available, only checking basic syntax"
    import json
    def testf(fn):
        print "Testing %s..." % fn
        void = json.load(open(fn))

def testd(arg, dirname, fnames):
    for fn in fnames:
        if fn.endswith('.json') and not fn.startswith('.#'):
            testf(os.path.join(dirname, fn))

os.path.walk('datamodel', testd, None)
